export {default as author} from 'schemas/author'
export {default as post} from 'schemas/post'
export {default as figure} from 'schemas/rich-text/figure'
export {default as richText} from 'schemas/rich-text/richText'
export {default as youtube} from 'schemas/rich-text/youtube'
export {default as settings} from 'schemas/settings'
export {default as tag} from 'schemas/tag'
